import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { execSync } from "node:child_process";
import * as readline from "node:readline";
import type { AppDeployment, DeployConfig, EmbarkConfig } from "./embark-config";
import { findRootDomainPackage, readEmbarkConfig } from "./embark-config";

const ROOT = join(import.meta.dirname, "..");
const PACKAGES_DIR = join(ROOT, "packages");

function validateCamelCase(name: string): boolean {
  // Accepts camelCase and kebab-case, then converts to camelCase if needed
  return /^[a-z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*$/.test(name);
}

function validateSubdomain(subdomain: string): boolean {
  // Subdomain: lowercase letters, numbers, hyphens; 1-63 chars; no leading/trailing hyphens
  return /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$/.test(subdomain);
}

function convertToCamelCase(name: string): string {
  return name
    .split("-")
    .map((part, idx) =>
      idx === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join("");
}

async function getInput(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function getRequiredInput(question: string, fieldName: string): Promise<string> {
  let value = "";
  while (!value) {
    value = await getInput(question);
    if (!value) {
      console.log(`❌ ${fieldName} is required\n`);
    }
  }
  return value;
}

function buildNetlifyToml(publishDir: string): string {
  return `[build]
  publish = "${publishDir}"
`;
}

async function createPackage() {
  console.log("📦 Package Creator - embark\n");

  // Ask for project name
  let projectName = "";
  while (!projectName || !validateCamelCase(projectName)) {
    projectName = await getInput("📝 Name (camelCase or kebab-case): ");

    if (!projectName || !validateCamelCase(projectName)) {
      console.log(
        "❌ Invalid name. Use only letters, numbers, and hyphens (e.g. my-package)\n",
      );
    }
  }

  const camelCaseName = convertToCamelCase(projectName);

  // Ask for title
  const title = await getRequiredInput("\n🏷️  Title (human-readable, e.g. 'My Awesome App'): ", "Title");

  // Ask for description BEFORE domain setup
  const description = await getRequiredInput("\n📄 Description: ", "Description");

  // Ask about root domain deployment FIRST
  const existingRootPkg = await findRootDomainPackage(PACKAGES_DIR);
  let rootDomain = false;

  const rootAnswer = await getInput("\n🌍 Deploy to root domain (domain.com) instead of a subdomain? [y/N]: ");
  if (rootAnswer.toLowerCase() === "y") {
    console.log("\n⚠️  WARNING: Only ONE package can be deployed to the root domain.");
    console.log("   → No other package can use the root domain without replacing this one.");
    console.log("   → All other packages must use a subdomain (e.g. app.domain.com).");

    if (existingRootPkg && existingRootPkg.name !== camelCaseName) {
      console.log(`\n⚠️  WARNING: Package "${existingRootPkg.name}" is already configured for the root domain.`);
      console.log(`   → Replacing it means "${existingRootPkg.name}" will NO LONGER be accessible at domain.com.`);
      console.log(`   → "${existingRootPkg.name}"'s .embark.jsonc will be updated to remove root domain access.`);
      console.log(`   → You must redeploy "${existingRootPkg.name}" with a subdomain to restore its access.`);

      const firstConfirm = await getInput(`\n⚠️  Replace "${existingRootPkg.name}" with "${camelCaseName}" as root domain package? [y/N]: `);
      if (firstConfirm.toLowerCase() === "y") {
        console.log(`\n⚠️  FINAL WARNING: "${existingRootPkg.name}" will permanently lose root domain access.`);
        console.log("   This action is irreversible unless you manually edit .embark.jsonc.");
        const finalConfirm = await getInput(`⚠️  Confirm replacement? [y/N]: `);
        if (finalConfirm.toLowerCase() === "y") {
          // Remove rootDomain from the existing package
          try {
            const prevConfig = await readEmbarkConfig(existingRootPkg.dir);
            if (prevConfig) {
              const updated = { ...prevConfig, rootDomain: false };
              const content = `// This file is auto-generated by Embark. Do not remove.\n// Edit these fields to update your package configuration.\n${JSON.stringify(updated, null, 2)}\n`;
              await writeFile(`${existingRootPkg.dir}/.embark.jsonc`, content);
              console.log(`  ✓ Removed root domain from "${existingRootPkg.name}"`);
            }
          } catch {
            console.log(`  ⚠ Warning: Could not update "${existingRootPkg.name}"'s config. Please edit it manually.`);
          }
          rootDomain = true;
        } else {
          console.log("  ℹ Root domain replacement cancelled. Using subdomain instead.");
        }
      } else {
        console.log(`  ℹ Keeping "${existingRootPkg.name}" as root domain package. Using subdomain instead.`);
      }
    } else {
      const confirm = await getInput(`\n⚠️  Confirm: deploy "${camelCaseName}" to the root domain (domain.com)? [y/N]: `);
      if (confirm.toLowerCase() === "y") {
        rootDomain = true;
      } else {
        console.log("  ℹ Using subdomain deployment instead.");
      }
    }
  }

  // Ask for subdomain only if not deploying to root domain
  let subdomain = "";
  if (!rootDomain) {
    while (!subdomain || !validateSubdomain(subdomain)) {
      subdomain = await getInput(`\n🌐 Subdomain (e.g. 'my-app' → my-app.embark.dev) [default: ${camelCaseName.toLowerCase()}]: `);

      if (!subdomain) {
        subdomain = camelCaseName.toLowerCase();
      }

      if (!validateSubdomain(subdomain)) {
        console.log(
          "❌ Invalid subdomain. Use lowercase letters, numbers, and hyphens only.\n",
        );
        subdomain = "";
      }
    }
  }

  // Ask for deploy target
  const deployAnswer = await getInput(
    "\n🚀 Deploy target:\n  1. GCP - Google Cloud Run (generates workflow + Dockerfile)\n  2. Netlify (generates workflow)\n  3. Cloudflare Pages (generates workflow with DNS setup)\n  4. Cloudflare Workers (generates workflow for serverless backend)\n  5. Other (custom deploy — you must create the workflow manually)\n  Choose [1/2/3/4/5]: ",
  );

  let appDeployment: AppDeployment = "gcp";
  if (deployAnswer === "2") {
    appDeployment = "netlify";
  } else if (deployAnswer === "3") {
    appDeployment = "cloudflare-pages";
  } else if (deployAnswer === "4") {
    appDeployment = "cloudflare-workers";
  } else if (deployAnswer === "5") {
    appDeployment = "other";
  }

  // Ask for workflowGen (boolean)
  const workflowAnswer = await getInput(
    appDeployment === "other"
      ? "\n🔄 Auto-generate a generic CI/CD workflow (you add the deploy steps)? [Y/n]: "
      : "\n🔄 Auto-generate GitHub Actions workflow? [Y/n]: ",
  );
  const workflowGen = workflowAnswer.toLowerCase() !== "n";

  // Ask about Git submodules
  const submoduleAnswer = await getInput(
    "\n🔗 Does this package use Git submodules? [y/N]: ",
  );
  const useSubmodule = submoduleAnswer.toLowerCase() === "y";

  // Ask for cloudflareUse
  let cloudflareUse = false;
  if (appDeployment === "cloudflare-pages") {
    const domainAnswer = await getInput(
      "\n🌐 Publish under a custom domain (e.g. app.yourdomain.com)? [Y/n]: ",
    );
    cloudflareUse = domainAnswer.toLowerCase() !== "n";
  } else if (appDeployment === "cloudflare-workers") {
    const domainAnswer = await getInput(
      "\n🌐 Publish under a custom domain (e.g. api.yourdomain.com)? [Y/n]: ",
    );
    cloudflareUse = domainAnswer.toLowerCase() !== "n";
  } else if (appDeployment !== "other") {
    const cloudflareAnswer = await getInput(
      "\n☁️  Use Cloudflare for custom domain/DNS setup? [Y/n]: ",
    );
    cloudflareUse = cloudflareAnswer.toLowerCase() !== "n";
  }

  const packageDir = join(PACKAGES_DIR, camelCaseName);
  const srcDir = join(packageDir, "src");

  console.log(`\n🚀 Creating package: ${camelCaseName}`);
  console.log(`   Title: ${title}`);
  console.log(`   Domain: ${rootDomain ? "root (domain.com)" : `${subdomain}.domain.com`}`);
  console.log(`   Deploy: ${appDeployment}`);
  console.log(`   Workflow: ${workflowGen ? "auto-generate" : "manual"}`);
  console.log(`   Cloudflare: ${cloudflareUse ? "yes" : "no"}`);

  try {
    await mkdir(packageDir, { recursive: true });
    await mkdir(srcDir, { recursive: true });
    console.log(`  ✓ Created directory: packages/${camelCaseName}`);

    await createBaseFiles(camelCaseName, packageDir, srcDir, title, subdomain, description);

    if (appDeployment === "netlify") {
      const netlifyToml = buildNetlifyToml("dist");
      await writeFile(join(packageDir, "netlify.toml"), netlifyToml);
      console.log(`  ✓ Created: netlify.toml`);
    }

    const deployConfig: DeployConfig = {
      appDeployment,
      cloudflareUse,
      workflowGen,
    };

    await writeEmbarkConfig(packageDir, {
      deploy: deployConfig,
      name: camelCaseName,
      title,
      ...(rootDomain ? { rootDomain: true } : { subdomain }),
      description,
      useSubmodule,
    });

    try {
      execSync(`git add packages/${camelCaseName}/`, { cwd: ROOT, stdio: "inherit" });
    } catch {
      console.log(`  ⚠ Warning: Could not add to git automatically`);
    }

    console.log(`\n✅ Package created successfully!\n`);
    console.log(`Next steps:`);
    console.log(`  1. Edit packages/${camelCaseName}/src/index.ts`);
    console.log(`  2. Run: bun install`);
    if (workflowGen) {
      if (appDeployment === "other") {
        console.log(`  3. Commit your changes (generic workflow will be generated — add your deploy steps to it)`);
      } else {
        console.log(`  3. Commit your changes (workflow will be generated automatically)`);
      }
    } else {
      console.log(`  3. Commit your changes (no workflow will be auto-generated)`);
    }
    console.log();
  } catch (error) {
    console.error(`\n❌ Error creating package:`, error);
    process.exit(1);
  }
}

async function createBaseFiles(
  camelCaseName: string,
  packageDir: string,
  srcDir: string,
  title: string,
  _subdomain: string,
  description: string,
): Promise<void> {
  const tsconfig = {
    extends: "../../tsconfig.json",
    compilerOptions: {
      composite: true,
      outDir: "./dist",
    },
    include: ["src/**/*"],
  };

  await writeFile(join(packageDir, "tsconfig.json"), JSON.stringify(tsconfig, null, 2) + "\n");
  console.log(`  ✓ Created: tsconfig.json`);

  const packageJson = {
    name: `@embark/${camelCaseName}`,
    description,
    version: "0.0.1",
    private: true,
    type: "module",
  };

  await writeFile(
    join(packageDir, "package.json"),
    JSON.stringify(packageJson, null, 2) + "\n",
  );
  console.log(`  ✓ Created: package.json`);

  const indexTs = `// ${camelCaseName}\n\nexport function hello(): string {\n  return "Hello from ${camelCaseName}";\n}\n`;
  await writeFile(join(srcDir, "index.ts"), indexTs);
  console.log(`  ✓ Created: src/index.ts`);
}

async function writeEmbarkConfig(
  packageDir: string,
  config: EmbarkConfig,
): Promise<void> {
  const configContent = `// This file is auto-generated by Embark. Do not remove.
// Edit these fields to update your package configuration.
${JSON.stringify(config, null, 2)}
`;
  await writeFile(join(packageDir, ".embark.jsonc"), configContent);
  console.log(`  ✓ Created: .embark.jsonc`);
}

if (import.meta.main) {
  createPackage().catch((error) => {
    console.error("[create-package] error:", error);
    process.exit(1);
  });
}
