name: Deploy release

on:
  push:
    branches: [main]
    paths:
      - "packages/release/**"
  workflow_dispatch:

env:
  PACKAGE_PATH: packages/release
  SUBDOMAIN: release
  DOMAIN: ${{ secrets.DOMAIN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          release-type: node
